name: Docker Image CI

on:
  push:
    tags: [ "v*" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
       name: Login to Docker Hub
       uses: docker/login-action@v1
       with:
         username: ${{ secrets.DOCKER_HUB_USERNAME }}
         password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Docker build
        run: /usr/bin/docker build . --tag ${{ github.repository }}:1.60.0
      - name: Docker push
        run: /usr/bin/docker push ${{ github.repository }}:1.60.0
